surveillanceapp/urls.py
from django.urls import path, include
from . import views

app_name = 'surveillanceapp'

urlpatterns=[
    path('', views.index, name='index'),
    path('stations/', views.list_stations, name='stationlist'),
    path('stations/<int:pk>', views.station_detail, name='stationdetails'),
    path('stations/<int:station_id>/videos/<int:video_id>', views.surveillance_video, name='video'),
    path('stations/addnewstation/', views.addNewStation, name='stationcreate'),
    path('stations/<int:station_id>/analysis/<int:video_id>', views.surveillance_report, name='report'),
    path('analytics/',views.analytics, name='analytics'),
    path('analytics/filter',views.filter_analytics, name='filter_analytics')
]

trafficsurveillance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('surveillanceapp.urls')),
]

surveillanceapp/models.py
from django.db import models
from django.conf import settings
import os
import re

# Check below by replacing with BASE_DIR from settings
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# class for station
class Station(models.Model):
    station_id = models.AutoField(primary_key=True)  ##surveillance station id
    station_name = models.CharField(max_length=50)   #station name
    lat_pos = models.FloatField() #latitude position
    lon_pos = models.FloatField() #longitude position
    station_pic = models.ImageField(upload_to='station_img/', default='default/defaultstation.png')  #Media will be uploaded to MEDIA_ROOT/station_img

    def __str__(self):
        return self.station_name


## surveillance video class, this class has many to one relation with Station class
class SurveillanceVideo(models.Model):
    video_id = models.AutoField(primary_key=True)
    timestamp = models.DateTimeField()  # we will be manually adding videos of different days so don't add autonow
    station = models.ForeignKey(Station, on_delete=models.CASCADE, related_name='surveillance_videos')
    thumbnail_filename = models.CharField(max_length=200,null=True)
    video_name = models.CharField(max_length=100, null=True)
    video_filename = models.CharField(max_length=200, null=True)
    report = models.BooleanField(default=False)
    lane_dimens = models.CharField(max_length=200, null=True)
    duration = models.BigIntegerField(null=True)
    analysed_duration = models.BigIntegerField(default=0)
    analysed_percentage = models.IntegerField(default=0)
    last_analysed = models.DateTimeField(null=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        print('Model save was called')
        super(SurveillanceVideo, self).save()

    def __str__(self):
        return str(self.video_name)

    # parse lane_dimensn and retrieve list of points
    def parsedimens(self):
        pattern = r'\[(\d+,\d+)\]'
        points = re.finditer(pattern, self.lane_dimens)
        point_list = []
        for point in points:
            point = point.group()
            point = [int(each) for each in point.lstrip('[').rstrip(']').split(',')]
            point_list.append(point)
        return point_list


##Surveillance Report Class has one to one relation with Surveillance Video class
class SurveillanceReport(models.Model):
    report_id = models.AutoField(primary_key=True)
    video = models.OneToOneField(SurveillanceVideo, on_delete=models.CASCADE, related_name='surveillance_report')
    congestion_jsonfile = models.CharField(null=True, max_length=100)
    count_jsonfile = models.CharField(null=True, max_length=100)
    contribution_jsonfile = models.CharField(null=True, max_length=100)
    report_file = models.CharField(null=True, max_length=100)
    avg_congestion_index = models.FloatField(default=0)
    avg_count_index = models.FloatField(default=0)
    outgoing_vehicle_count = models.IntegerField(default=0)
    outgoing_tempo_count = models.IntegerField(default=0)
    outgoing_bike_count = models.IntegerField(default=0)
    outgoing_car_count = models.IntegerField(default=0)
    outgoing_taxi_count = models.IntegerField(default=0)
    outgoing_micro_count = models.IntegerField(default=0)
    outgoing_pickup_count = models.IntegerField(default=0)
    outgoing_bus_count = models.IntegerField(default=0)
    outgoing_truck_count = models.IntegerField(default=0)

    def __str__(self):
        identifier = 'Report {} for {}'.format(self.report_id,self.video.video_name)
        return identifier

    def getCountList(self):
        pass

    def getAvgCapacity(self):
        pass

    def getAvgCount(self):
        pass

surveillanceapp/forms.py
from django import forms
from .models import *
import os
from django.conf import settings
import cv2
import math
from . import cvrender

class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = ['station_name', 'lat_pos', 'lon_pos', 'station_pic']


class VideoAdminForm(forms.ModelForm):
    def clean(self):
        formdata = self.cleaned_data
        entered_filename = formdata.get('video_filename')
        station = formdata.get('station')
        actual_filename = os.path.join(settings.VIDEO_DIR, station.station_name, entered_filename)
        try:
            with open(actual_filename, 'r') as videofile:
                pass
            return formdata
        except FileNotFoundError:
            raise forms.ValidationError('Entered File has not been saved in the video directory yet!')

    # def save(self, commit=True):
    #     video = super(VideoAdminForm, self).save(commit=False)
    #     actual_filename = os.path.join(settings.VIDEO_DIR, video.video_filename)
    #     unique_name = '{}_{}_{}'.format(str(video.station), str(video.timestamp.date()),str(video.timestamp.time()))
    #     fileext = os.path.splitext(video.video_filename)[1]
    #     print('The entered name was {} but the new name is {}'.format(video.video_filename,unique_name+fileext))
    #     self.instance.video_filename = unique_name+fileext
    #     self.instance.video_name = unique_name
    #     new_filename = os.path.join(settings.VIDEO_DIR, video.video_filename)
    #     os.rename(actual_filename,new_filename)
    #     # extracting a thumbnail and saving as an image
    #     cap = cv2.VideoCapture(new_filename)
    #     cap.set(cv2.CAP_PROP_POS_MSEC, 10000)   # capture a frame at position 10 seconds from the start
    #     self.instance.duration = math.ceil((cap.get(cv2.CAP_PROP_FRAME_COUNT)/cap.get(cv2.CAP_PROP_FPS))/60)  # Finds the duration in minutes
    #     ret, frame = cap.read()
    #     if ret:
    #         thumbnail_filename = os.path.join('video_thumbnails','{}.jpg'.format(unique_name))
    #         thumbnail_path = os.path.join(settings.BASE_DIR,'static',thumbnail_filename)
    #         frame = cvrender.overlap_play(frame)
    #         cv2.imwrite(thumbnail_path, frame)
    #         self.instance.thumbnail_filename = thumbnail_filename
    #         print('Done')
    #     cap.release()
    #
    #     print('Now saving at {}'.format(thumbnail_path))
    #     return self.instance

    class Meta:
        model = SurveillanceVideo
        fields = ['timestamp', 'station', 'video_filename', 'lane_dimens', 'duration']

surveillanceapp/views.py
from django.shortcuts import render, redirect, Http404, HttpResponse
from .models import Station,SurveillanceVideo,SurveillanceReport
from django.views.generic import ListView,DetailView
from .forms import *
from . import cvrender
import cv2
import json
import numpy as np
import datetime
import os
import re
from django.conf import settings


def index(request):
    title = "Dashboard"
    stations_data = Station.objects.all()
    stationCount = Station.objects.count()
    vehicleCount = 0
    for report in SurveillanceReport.objects.all():
        vehicleCount += report.outgoing_vehicle_count
    context = {
        'title': title,
        'stations': stations_data,
        'stationCount': stationCount,
        'videoCount': SurveillanceVideo.objects.count(),
        'reportCount': SurveillanceReport.objects.count(),
        'vehicleCount': vehicleCount
    }
    return render(request,'surveillanceapp/index.html',context)


def addNewStation(request):
    if request.method == 'POST':
        received = request.POST.copy()
        print(received)
        form = StationForm(request.POST, request.FILES)
        if form.is_valid():
            station = form.save(commit=False)
            os.mkdir(os.path.join(settings.VIDEO_DIR, station.station_name))     #Create a new folder to store the videos of that station
            station.save()
            return redirect('surveillanceapp:stationdetails', pk=station.station_id)
    else:
        form = StationForm()

    return render(request, 'surveillanceapp/addnewstation.html', {'form': form})


def list_stations(request):
    try:
        stations = Station.objects.all()
        station_list = []
        for station in stations:
            total_videos = 0
            analysed_videos = 0
            for video in station.surveillance_videos.all():
                if video.report:
                    analysed_videos += 1
                total_videos += 1
            if total_videos == 0:
                percent = 0
            else:
                percent = int(analysed_videos/total_videos*100)
            station_list.append({
                'station': station,
                'progress': {
                    'total': total_videos,
                    'analysed': analysed_videos,
                    'percent': percent
                }
            })
    except Station.DoesNotExist:
        raise Http404
    return render(request, 'surveillanceapp/stationlist.html', {'title': 'Station List', 'station_list': station_list})


def station_detail(request, pk):
    try:
        station = Station.objects.get(pk=pk)
        folder_name = station.station_name
        search_dir = os.path.join(settings.VIDEO_DIR, folder_name)

        for file in os.scandir(search_dir):
            stats = os.stat(file.path)
            timestamp = datetime.datetime.fromtimestamp(stats.st_ctime)

            # New updated video naming style
            access_time = timestamp.strftime('%Y_%m_%d_%H_%M_%S')
            pattern = r'[a-zA-Z]+_\d{4}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}\.\w{3,}'

            if not re.match(pattern, file.name):
                # This means a new video is added to that folder
                print(file.name, 'in ', folder_name, ' does not match the pattern')
                unique_name = '{}_{}'.format(folder_name, access_time)
                fileext = os.path.splitext(file.name)[1]

                video_name = unique_name    # The unique name to be used for JSON files as well

                video_filename = unique_name + fileext    # The full path to the video file

                # New updated video naming style
                video_path = os.path.join(settings.VIDEO_DIR, folder_name, video_filename)
                os.rename(file.path, video_path)    # To rename the video file according to our standards

                # extracting a thumbnail and saving as an image
                cap = cv2.VideoCapture(video_path)
                cap.set(cv2.CAP_PROP_POS_MSEC, 10000)  # capture a frame at position 10 seconds from the start
                duration = math.ceil((cap.get(cv2.CAP_PROP_FRAME_COUNT) / cap.get(cv2.CAP_PROP_FPS)))  # Finds the duration in seconds
                ret, frame = cap.read()
                if ret:
                    thumbnail_filename = os.path.join('video_thumbnails', '{}.jpg'.format(unique_name))
                    thumbnail_path = os.path.join(settings.BASE_DIR, 'static', thumbnail_filename)
                    frame = cvrender.overlap_play(frame)
                    cv2.imwrite(thumbnail_path, frame)
                    print('Thumbnail created and saved')
                cap.release()

                # Now create a new Surveillance Video model to save the new video
                newvideo = SurveillanceVideo.objects.create(station=station,
                                                            video_name=video_name,
                                                            video_filename=video_filename,
                                                            timestamp=timestamp,
                                                            duration=duration,
                                                            thumbnail_filename=thumbnail_filename)

                print('New Video found and added: {}, {}, {}, {}'.format(newvideo.video_filename,newvideo.timestamp,newvideo.thumbnail_filename,newvideo.duration))
        videolist = SurveillanceVideo.objects.filter(station_id=pk).order_by('-timestamp')
        return render(request, 'surveillanceapp/stationdetails.html', {'station': station, 'videolist': videolist})

    except Station.DoesNotExist:
        raise Http404


def surveillance_video(request,station_id,video_id):
    video = SurveillanceVideo.objects.get(video_id=video_id)
    print(video.video_name)
    print(video.report)
    return render(request, 'surveillanceapp/video.html', {'video': video})


def surveillance_report(request,station_id,video_id):

    report = SurveillanceReport.objects.get(video__video_id=video_id)

    with open(os.path.join(settings.COUNT_JSON_DIR, report.count_jsonfile), 'r') as countfile:
        countdata = json.load(countfile)

    with open(os.path.join(settings.CONGESTION_JSON_DIR, report.congestion_jsonfile), 'r') as congestionfile:
        congestiondata = json.load(congestionfile)

    with open(os.path.join(settings.CONTRIB_JSON_DIR, report.contribution_jsonfile), 'r') as contribfile:
        contribdata = json.load(contribfile)

    totalcount = []
    vclass_name = ['Tempo','Bike','Car','Taxi','Micro','Pickup','Bus','Truck']
    vclass_count = [[] for each in vclass_name]
    for data in countdata:
        for i in range(len(data)):
            vclass_count[i].append(data[i])
        totalcount.append(sum(data))

    # Congestion contribution from area approach
    avg_congestion = sum(congestiondata) / len(congestiondata)
    vclass_contrib = [[] for each in vclass_name]
    for i, data in enumerate(contribdata):
        actual_contrib = np.array(data) * congestiondata[i]
        for i in range(len(data)):
            vclass_contrib[i].append(actual_contrib[i])
    avg_contrib = [(sum(contrib) / len(contrib)) / avg_congestion for contrib in vclass_contrib]
    avg_contrib = np.round(avg_contrib, 3)

    #Congestion contribution from count in bike units method
    outgoing_counts = [report.outgoing_tempo_count,
                       report.outgoing_bike_count,
                       report.outgoing_car_count,
                       report.outgoing_taxi_count,
                       report.outgoing_micro_count,
                       report.outgoing_pickup_count,
                       report.outgoing_bus_count,
                       report.outgoing_truck_count]
    vehicle_weights = [2,1,2,2,3,3,5,5] #This is to convert each vclass count into the bike units
    outgoing_counts = np.array(outgoing_counts) * np.array(vehicle_weights)
    count_avgcontrib = np.round(outgoing_counts/np.sum(outgoing_counts), 3)

    net_contrib = np.round((2/3)*count_avgcontrib + (1/3)*avg_contrib, 3).tolist()  #[2/3 * countbased + 1/3 * areabased]

    # Rolling average of congestion sampled over a window of 5 seconds
    interval = int(math.ceil(0.1*len(countdata)))
    rolling_avg_congestion = np.convolve(np.array(congestiondata), np.ones((interval,)) / interval, mode='same').tolist()
    rolling_avg_congestion = [float(each) for each in rolling_avg_congestion]

    # Rolling average of total no. of vehicles sampled over a window of 5 seconds
    rolling_avg_count = np.convolve(np.array(totalcount), np.ones((interval,)) / interval, mode='same').tolist()
    rolling_avg_count = [float(each) for each in rolling_avg_count]

    count_chart = []
    count_dump = []
    vcount_series = [{} for each in vclass_name]
    for i in range(0, len(vclass_name)):
        vcount_series[i] = {
            'name': vclass_name[i],
            'data': vclass_count[i],
        }
        count_chart.append({
            'chart': {'type': 'line'},
            'plotOptions': {
                'series': {
                    'pointStart': 1
                }
            },
            'title': {'text': 'No.of {} in the road vs time'.format(vclass_name[i])},
            'xAxis': {'title': {'text': 'Time'}},
            'yAxis': {'title': {'text': vclass_name[i]+' Count'}},
            'series': [vcount_series[i]],
            'credits': {'enabled': False}
        })
        count_dump.append(json.dumps(count_chart[i]))

    totalcount_chart = json.dumps({
        'chart': {'type': 'line'},
        'title': {'text': 'Plot of total no. of vehicles in road vs time'},
        'xAxis': {'title': {'text': 'Time'}},
        'yAxis': {'title': {'text': 'No.of Vehicles'}},
        'series': [{'name': 'No.of vehicles', 'data': totalcount}],
        'credits': {'enabled': False}
    })

    totalcount_roll_chart = json.dumps({
        'chart': {'type': 'line'},

surveillanceapp/templates/surveillanceapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {#  <link rel="shortcut icon" href="img/favicon.png">#}

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.css'%}" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="{%  static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
    <link href="{%  static 'fontawesome/css/all.css' %}" rel="stylesheet" />
    <!-- Custom styles -->
    <!--<link rel="stylesheet" href="css/fullcalendar.css">-->
    <link href="{%  static 'css/widgets.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{%  static 'css/style-responsive.css' %}" rel="stylesheet" />
    <link href="{% static 'css/xcharts.min.css' %}" rel=" stylesheet">
    <link href="{%  static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}"></script>

    <title>{{ title }}</title>

    {% block extracss %}
    {% endblock %}

    {% block extraheadjs %}
    {% endblock %}

</head>

<body>
  <!-- container section start -->
    <section id="container" class="">

        <header class="header dark-bg">
          <div class="toggle-nav">
            <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
          </div>

          <!--logo start-->
          <a href="{%  url 'surveillanceapp:index' %}" class="logo">TRAFFIC COUNT AND CONGESTION SURVEILLANCE</a>
          <!--logo end-->


        </header>
        <!--header end-->

        <!--sidebar start-->
        <aside>
          <div id="sidebar" class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu">
              <li class="active">
                <a class="" href="{%  url 'surveillanceapp:index' %}">
                      <i class="icon_house_alt"></i>
                      <span>Dashboard</span>
                  </a>
              </li>
            <li class="active" >
            <a class="" href="{% url 'surveillanceapp:stationlist' %}">
                  <i class="fas fa-map-marked-alt"></i>
                  <span>Stations</span>
              </a>
          </li>
            <li class="active">
            <a class="" href="{% url 'surveillanceapp:analytics' %}">
                  <i class="icon_datareport_alt"></i>
                  <span>Analytics</span>
            </a>
          </li>

                <li class="active">
            <a class="" href="#">
                  <i class="icon_book"></i>
                  <span>Documentation</span>
              </a>
          </li>
            </ul>
            <!-- sidebar menu end-->
          </div>
        </aside>
        <!--sidebar end-->

        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                {% block main-content %}
                {% endblock %}
            </section>
        </section>

    </section>

    <!-- bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- nice scroll -->
    <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>

    <!--custom script for all page-->
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block extrajs %}
    {% endblock %}

</body>

</html>

surveillanceapp/templates/surveillanceapp/report.html
{% extends 'surveillanceapp/base.html' %}
{% load static %}

{% block extracss %}
    <style>
        .vehicle-img{
            width: 152px;
            height: 152px;
            display: block;
        }
        .vehicle-block{
            border-width: 5px;
            border-style: solid;
            border-color: #394a59;
            margin-left: 1%;
            margin-right: 1%;
            text-align: center;
            display: inline-block;
        }
        .vehicle-block p{
            font-size: 150%;
            color: #394a59;
        }
        .outgoing-count{
            font-weight: bold;
            font-size: 200%;
            margin-top: -2%;
            color: #394A59;
        }
        .btn{
            padding-top: 2% !important;
            padding-bottom: 2% !important;
        }
        .btn-text{
            font-size: 150%;
            font-weight: bold;
        }

    </style>
{% endblock %}

{% block extraheadjs %}
    <script src="{% static 'js/highcharts.js' %}"></script>
{% endblock %}

{% block main-content %}
    <div class="row">
        <div class="col-lg-8">
            <ol class="breadcrumb" style="margin-bottom: 0%;">
              <li><i class="fa fa-home"></i><a href="{% url 'surveillanceapp:index' %}">Home</a></li>
                <li><i class="fas fa-map-marked-alt"></i><a href="{% url 'surveillanceapp:stationlist' %}">Stations</a></li>
                <li><i class="fas fa-map-marker-alt"></i><a href="{% url 'surveillanceapp:stationdetails' report.video.station.station_id %}">{{ report.video.station.station_name }}</a></li>
                <li><i class="fas fa-camera"></i><a href="{% url 'surveillanceapp:video' report.video.station.station_id report.video.video_id %}">Video</a></li>
              <li><i class="fas fa-chart-bar"></i>Analysis Report</li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a id="replay-btn" href="{% url 'surveillanceapp:video' report.video.station.station_id report.video.video_id %}" class="btn btn-block btn-primary">
                <span class="fas fa-play-circle fa-2x" style="margin-right: 6%;"> </span> <span class="btn-text"> Re-analyze Video</span>
            </a>
        </div>
        <div class="col-lg-2">
            <a id="export-pdf" href="{% static report.report_file %}" target="_blank" class="btn btn-block btn-danger">
                <span class="fas fa-file-pdf fa-2x" style="margin-right: 6%;"> </span> <span class="btn-text"> Export to PDF</span>
            </a>
        </div>
    </div>
    <div class="row" style="margin-top: 1%">
        <div class="col-lg-12">
            <section class="panel panel-default">
              <div class="panel-heading">
                  Report
              </div>
            <div class="panel-body">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#voverview" data-target="#voverview" data-toggle="tab">Overview</a>
                    </li>
                    <li><a href="#vcount" data-target="#vcount" data-toggle="tab">Count Graphs</a>
                    </li>
                    <li><a href="#vcongestion" data-toggle="tab" data-target="#vcongestion">Congestion Graphs</a>
                    </li>
                    <li><a href="#vcontribution" data-toggle="tab" data-target="#vcontribution">Congestion Contribution Chart</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active fade in" id="voverview">
                        <div class="row" style="margin-top: 2%; padding-left: 4%; padding-right: 3%">
                            <div style="font-size: 150%">
                                This surveillance report for <strong>{{ report.video.station.station_name }}</strong> station has been generated by the analysis of <strong>{{ report.video.analysed_percentage }}%</strong> of the video.
                            </div>
                        </div>
                        <div id="vehicle-wrapper" class="row" style="margin-top: 2%;">
                            <p style="font-size: 150%; padding-left: 4%">Total number of outgoing vehicles during this period:</p>
                            <div class="col-lg-12" style="text-align: center;">
                                <div class="vehicle-block">
                                    <img src="{% static 'img/tempo.png' %}" class="vehicle-img">
                                    <p>Tempo</p>
                                    <h2 class="outgoing-count" data-vclass="Tempo">{{ report.outgoing_tempo_count }}</h2>
                                </div>
                                <div class="vehicle-block">
                                    <img src="{% static 'img/bike.png' %}" class="vehicle-img">
                                    <p>Bike</p>
                                    <h2 class="outgoing-count" data-vclass="Bike">{{ report.outgoing_bike_count }}</h2>
                                </div>
                                <div class="vehicle-block">
                                    <img src="{% static 'img/car.png' %}" class="vehicle-img">
                                    <p>Car</p>
                                    <h2 class="outgoing-count" data-vclass="Car">{{ report.outgoing_car_count }}</h2>
                                </div>
                                <div class="vehicle-block">
                                    <img src="{% static 'img/taxi.png' %}" class="vehicle-img">
                                    <p>Taxi</p>
                                    <h2 class="outgoing-count" data-vclass="Taxi">{{ report.outgoing_taxi_count }}</h2>
                                </div>
                                <div class="vehicle-block">
                                    <img src="{% static 'img/micro.png' %}" class="vehicle-img">
                                    <p>Micro</p>
                                    <h2 class="outgoing-count" data-vclass="Micro">{{ report.outgoing_micro_count }}</h2>
                                </div>
                                <div class="vehicle-block">
                                    <img src="{% static 'img/pickup.png' %}" class="vehicle-img">
                                    <p>Pickup</p>
                                    <h2 class="outgoing-count" data-vclass="Pickup">{{ report.outgoing_pickup_count }}</h2>
                                </div>
                                <div class="vehicle-block">
                                    <img src="{% static 'img/bus.png' %}" class="vehicle-img">
                                    <p>Bus</p>
                                    <h2 class="outgoing-count" data-vclass="Bus">{{ report.outgoing_bus_count }}</h2>
                                </div>
                                <div class="vehicle-block">
                                    <img src="{% static 'img/truck.png' %}" class="vehicle-img">
                                    <p>Truck</p>
                                    <h2 class="outgoing-count" data-vclass="Truck">{{ report.outgoing_truck_count }}</h2>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 2%; padding-left: 3%; padding-right: 3%">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <i class="fa fa-info-circle"></i> Overall Summary
                                </div>
                                <div class="panel-body">
                                    <div style="font-size: 150%">
                                        <p>Total number of outgoing vehicles:   {{ report.outgoing_vehicle_count }}</p>
                                        <p>Average congestion index over the entire duration:    {{ report.avg_congestion_index|floatformat:2 }}</p>
                                        <p>Average number of vehicles in the road at a time:  {{ report.avg_count_index|floatformat:2 }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane" id="vcount">
                        <div class="col-lg-12 col-md-12">
                         {% for vehicle in vclass_names %}
                             <div class="col-lg-6 panel panel-primary">
                                  <div class="panel-body" id="{{ vehicle }}count-graph"></div>
                             </div>
                         {% endfor %}
                        </div>
                    </div>

                    <div class="tab-pane col-lg-12" id="vcongestion">
                        <div class="col-lg-12 panel panel-primary">
                              <div class="panel-body" id="congest-graph"></div>
                        </div>
                        <div class="col-lg-12 panel panel-primary">
                              <div class="panel-body" id="congest-rollgraph"></div>
                        </div>
                        <div class="col-lg-12 panel panel-primary">
                              <div class="panel-body" id="totcount-graph"></div>
                        </div>
                        <div class="col-lg-12 panel panel-primary">
                              <div class="panel-body" id="totcount-rollgraph"></div>
                        </div>
                    </div>

                    <div class="tab-pane col-lg-12" id="vcontribution">
                        <div class="col-lg-12 panel panel-primary">
                              <div class="panel-body center-block" id="contrib-graph"></div>
                        </div>
                    </div>
                 </div>

             </div>
            </section>
    </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script>
        {% for chart in count_chart %}
            Highcharts.chart("{{ chart.class_name }}count-graph", {{ chart.chart|safe }});
        {% endfor %}

        Highcharts.chart('totcount-graph', {{ totalcount_chart|safe }});
        Highcharts.chart('totcount-rollgraph', {{ totalcount_roll_chart|safe }});

        Highcharts.chart('congest-graph', {{ congest_chart|safe }});
        Highcharts.chart('congest-rollgraph', {{ congest_roll_chart|safe }});

        Highcharts.chart('contrib-graph', {{ contrib_chart|safe }});

    </script>
{% endblock %}